# Google Collab text generation python notebook using HuggingFace

In [2]:
!pip install transformers
#!pip install einops
#!pip install tensorflow
from transformers import pipeline #AutoTokenizer, TFAutoModelForCausalLM,
 #using AutoModelForCausalLM then specifying the config seems to be the
#import tensorflow as tf


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 11.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 25.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 33.2 MB/s eta 0:00:00


In [3]:

#create list of prompts
#prompt1 = "Write a letter to your local newspaper stating your opinion on the effects computers have on people. Persuade the readers to agree with you." #the prompt to provide
# prompt2 = "Write a persuasive essay to a newspaper about censorship in libraries. Do you believe that certain materials, such as books, music, movies, and magazines should be removed from the shelves if they are found offensive? " #the prompt to provide
# prompt3 = "Write a 200 word response that explains how the features of the setting affect the cyclist in 'Rough Road Ahead' by Joe Kurmaski."
# prompt4 = "Why does Winter Hibiscus by Minfong Ho end with 'When they come back in the spring, when the snows melt and the geese return and this hibiscus is budding, then I will take that test again?'"
# prompt5 = "Write an essay about the mood created in the memoir 'From Home: The Blueprints of Our Lives' by Narciso Rodriguez."
# prompt6 = "Write an essay describing the obstacles the builders of the Empire State Building faced in allowing dirigibles to dock. Use information from 'The Mooring Mast' by Marcia Amidon Lüsted."
# prompt7 = "Being patient means that you are understanding and tolerant. A patient person experience difficulties without complaining. Write a true story about a time someone was patient using first person." #using first person. #the prompt to provide
# prompt8 = "Laughter is the shortest distance between two people. Laughter is important in any relationship. Write a true story involving laughter in first person." #using first person. #the prompt to provide
# prompts = ['prompt{}'.format(i) for i in range(1, 9)] #doesn't work

#prompts more suitable for gpt2
prompt1 = "Computers have many effects on people." #the prompt to provide
prompt2 = "I believe that censorship of materials in libraries"
prompt3 = "Features of the setting affect the cyclist in 'Rough Road Ahead' in many ways."
prompt4 = "The book Winter Hibiscus ends the way it does because"
prompt5 = "The mood created in the memoir 'From Home is'"
prompt6 = "The builders of the Empire State Building faced several obstacles in allowing dirigibles to dock."
prompt7 = "An example of a time someone in my life was patient was"
prompt8 = "One time I experienced laughter in my life was when"

prompts = [prompt1, prompt2, prompt3, prompt4, prompt5, prompt6, prompt7, prompt8]

essay_ids = [1, 2, 3, 4, 5, 6, 7, 8]
essay_id = 5 #an id of the essay to save to the text file
essay_type = "persuasive/narrative" #type of essay to potentially save
max_tokens = 50 #maximum number of tokens to include
n_return = 30 #number of essays to generate in single API call

### Using Pipeline and Zero-Shot Learning

In [4]:
model = "gpt2"
model2 = "tiiuae/falcon-7b-instruct"
model3 = "meta-llama/Llama-2-7b-chat-hf"
generator = pipeline('text-generation', model = model, trust_remote_code=True)


Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


In [ ]:
#testing
# text = generator(prompt5, max_length = 300, num_return_sequences=3)
# text[0]["generated_text"]
# text_gen = pipeline('text-generation', model = "bigscience/T0pp")
# text_gen(prompt5, max_length = 200, num_return_sequences = 3)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


### Final Generation Using Pipeline

See
- https://medium.com/@seema.singh/reading-and-writing-files-with-google-colaboratory-f0c234683946
- https://che-kulhan.medium.com/use-google-colaboratory-to-read-and-write-files-with-python-totally-online-d6aff435494e

Example Syntax from ChatGPT:
```

from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')

# Sample list of text strings
text_strings = ["This is the first text.", "Another text string.", "One more text."]

# Path to the directory where you want to save the text files
save_directory = '/content/drive/My Drive/TextFiles/'

# Iterate through the list and save each text string to a separate file
for i, text in enumerate(text_strings):
    filename = f"file{i+1}.txt"
    file_path = save_directory + filename
    with open(file_path, 'w') as f:
        f.write(text)

    print(f"File '{filename}' saved successfully.")

from google.colab import files

# Path to the directory containing the text files in Google Drive
file_directory = '/content/drive/My Drive/TextFiles/'

# List of text file names
file_names = ["file1.txt", "file2.txt", "file3.txt"]  # Replace with your file names

# Download each file to the local computer
for filename in file_names:
    files.download(file_directory + filename)


```

In [6]:
#set up saving the output ####

#import drive to save results to google drive
from google.colab import drive
drive.mount("/drive")

#path to directory
save_directory = "/drive/MyDrive/Colab Outputs/"

#count
count = 10159



Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).


In [7]:
#manually specify the count for the id number
count = 10159
count

10159

In [8]:
for m in range(15):

  for i in range(len(prompts)):

    for k in range(10):
      results = generator(prompts[i], max_length = 300, num_return_sequences= n_return)
      #print(results)

      for result in results:
        essay_id = f"eid{i + 1}"
        count = count + 1
        #print(result)
        #print(result["generated_text"])
        text = result["generated_text"]

        with open(f'{save_directory}{essay_id}_{model}_{count}.txt', 'w') as f:
                  f.write(text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end gene

KeyboardInterrupt: ignored

In [ ]:
"""
from google.colab import files

# Path to the directory containing the text files in Google Drive
file_directory = '/content/drive/My Drive/TextFiles/'

# List of text file names
file_names = ["file1.txt", "file2.txt", "file3.txt"]  # Replace with your file names

# Download each file to the local computer
for filename in file_names:
    files.download(file_directory + filename)
"""


### Distilgpt2 (for proof of concept)

In [ ]:
#load the tokenizer and model
model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = TFAutoModelForCausalLM.from_pretrained(model_name, pad_token_id=tokenizer.eos_token_id) #pad token argument recommended by https://huggingface.co/blog/how-to-generate

In [ ]:
#check model configuration
model.generation_config

GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 50256,
  "eos_token_id": 50256,
  "transformers_version": "4.27.4"
}

In [ ]:
#tokenize the prompt using model-specific tokenizer. see https://huggingface.co/docs/transformers/preprocessing
  #using padding as its is best practice
encoded_prompt5 = tokenizer(prompt5, return_tensors = 'tf')#, padding = True) #padding = True threw up errors so removed.
#attn_msk = encoded_prompt5["attention_mask"] #extracting attention mask
#input_ids = encoded_prompt5["input_ids"] #extracting input ids
encoded_prompt5 #includes an array of input ids an an array of attention mask

{'input_ids': <tf.Tensor: shape=(1, 28), dtype=int32, numpy=
array([[16594,   257,   939,  1573, 14268,   546,   262, 10038,  2727,
          287,   262, 24649,   705,  4863,  5995,    25,   383,  4518,
        17190,   286,  3954, 18965,     6,   416, 31987, 26786, 19391,
           13]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 28), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1]], dtype=int32)>}

There are a [variety of decoding strategies available](https://huggingface.co/docs/transformers/generation_strategies) in huggingface's `transformers` library. See the [huggingface blog](https://huggingface.co/blog/how-to-generate) for more information.
- `do_sample=True`: enables decoding strategies such as multinomial sampling, beam-search multinomial sampling, Top-K sampling and Top-p sampling.
- `max_new_tokens` = max_tokens: change max # of tokens
- `penatly_alpha = 0.6`:
- `top_k = 4`:
- `num_beams`: greater than 1 switches from greedy (default) to beam search.
- `num_return_sequences`: to return more than 1 sequence.



Different decoding methods:
```
#setup
prompt = "Hugging Face Company is"
inputs = tokenizer(prompt, return_tensors="pt")

#constrastive search
outputs = model.generate(**inputs, penalty_alpha=0.6, top_k=4, max_new_tokens=100)
tokenizer.batch_decode(outputs, skip_special_tokens=True)

#multinomial sampling
outputs = model.generate(**inputs, do_sample=True, max_new_tokens=100)
tokenizer.batch_decode(outputs, skip_special_tokens=True)

#beam search with multinomial sampling
outputs = model.generate(**inputs, num_beams=5, do_sample=True)
tokenizer.decode(outputs[0], skip_special_tokens=True)
```


In [ ]:
#configure the model to sample responses. see https://huggingface.co/docs/transformers/generation_strategies
outputs = model.generate(**encoded_prompt5) #, do_sample=True, max_new_tokens = max_tokens) #penatly_alpha = 0.6, top_k = 4  #save the encoded generated text as output

/usr/local/lib/python3.9/dist-packages/transformers/generation/tf_utils.py:745: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/transformers/generation/tf_utils.py:854: UserWarning: Using `max_length`'s default (20) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Input length of input_ids is 28, but `max_length` is set to 20. This can lead to unexpected behavior. You should consider increasing`max_new_tokens`.


InvalidArgumentError: ignored

In [ ]:
text = tokenizer.batch_decode(outputs, skip_special_tokens=True) #decode the generated text so it is now text.

NameError: ignored

In [ ]:
#Generating Text Using a Pipeline
# Setting up the pipeline
text_generator = pipeline(
    "text-generation",
    model=model_name,
    tokenizer=tokenizer,
    framework="tf",
    max_new_tokens=300
)

All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at distilgpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [ ]:
text_generator(prompt5)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'Write a 200 word essay about the mood created in the memoir \'From Home: The Blueprints of Our Lives\' by Narciso Rodriguez.\n\nThe book was written in a series of chapters in the series: \u202a "The Truth: A Year in a Nation\'s Story of Living Alone, a Memoir of Manhood and the Searching of the Life Through an Affair of Love.\u202aThe novel,\u202a is \u202a "From Home\u202a from the White House, a collection of books about the daily life of a White House resident who was never alone with his children at home\u202a in Washington. You\'ll also hear the stories and stories of people who were not here until they learned their way out.\u202a\u202a\u202a"With the book you\'ll read about each and every day, at best, but at worst… it will feel like the way you\'ve read \u202aThe Blueprints –\u202a" —and when it\'s over you\'ll find your way back to the White House: The Blueprints, which began in the autumn of 1999 and is published in New York by Penguin Classics.\nThe mem

/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py:1201: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "Hello, I'm a language modeler for the webcomic, which has a large audience. But it really does lack some of its essential features"},
 {'generated_text': "Hello, I'm a language modeler. I make lots of assumptions about how to build a language, how to optimize it and how to apply my"},
 {'generated_text': "Hello, I'm a language model, so it makes all of us do a little bit of thinking to learn the first part of programming, which I"}]

## Attempting with Falcon model

In [ ]:
model2 = "tiiuae/falcon-7b-instruct"
generator = pipeline('text-generation', model = model2)

In [ ]:
#set up saving the output ####

#import drive to save results to google drive
from google.colab import drive
drive.mount("/drive")

#path to directory
save_directory = "/drive/MyDrive/Colab Outputs/"

#count
count = 2954



In [ ]:


for i in range(len(prompts)):

  for k in range(10):
    results = generator(prompts[i], max_length = 300, num_return_sequences= n_return)
    print(results)

    for result in results:
      essay_id = i + 1
      count = count + 1
      print(result)
      print(result["generated_text"])
      text = result["generated_text"]

      with open(f'{save_directory}{essay_id}_{model}_{count}.txt', 'w') as f:
                f.write(text)

### Using OpHugging Face's gpt-J-6b model
https://huggingface.co/EleutherAI/gpt-j-6B

- paused for now. Consistently causes crashes due to insufficient RAM.

In [ ]:
#load the tokenizer and model
model_name = "EleutherAI/gpt-j-6B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

In [ ]:
#tokenize the prompt using model-specific tokenizer.
 #see https://huggingface.co/docs/transformers/preprocessing

encoded_prompt1 = tokenizer(prompt1, padding = True)



In [ ]:
#configure the model
model.generate(**inputs, num_beams=4, do_sample=True)